### ISSUE TITLE
Client changed nickname event?

### ISSUE THREAD

**Issue by ghost** [Murgeye/teamspeak3-python-bot#13]
Is this an event at client changed nickname?
Sorry i'm not try first because in telnet or ssh, when me register event, there isnt any event show.
So can it be achieved?
Thanks.

**Comment by ghost** [comment]
I am working on an account management system because:
1: In my country, myteamspeak is maliciously blocked
2: After a period of time, all the permissions were lost
But I found a huge problem: the client may change the nickname, which will lead to the immediate loss of permissions
So I want to capture the behavior of the client changing the nickname and prevent the above problems.
Thank you again for looking at this text wall.

**Comment by Murgeye** [comment]
I cannot test this right now, but I think there is no event sent by the server when a client changes a nickname. However, I would suggest tracking clients by their `cldbid` (client database id), since using the username might be unreliable (e.g. what happens if the user changes their nickname in between connections to the server?).

I am not 100% sure what your use case is, so let me know if this helps you.

**Comment by Murgeye** [comment]
I will close this for now. If this is not resolved, leave a comment please @gamecss.

**Comment by ghost** [comment]
> I will close this for now. If this is not resolved, leave a comment please @gamecss.

I'm sorry i have no time to see issue. Unfortunately, I make this account management system because cldbid is unreliable.

**Comment by ghost** [comment]
I guess if users don't login in for 30 days, server will change cldbid.

**Comment by Murgeye** [comment]
I just checked, and there seems to be no way of getting notified by the server about nickname changes. Your best bet would probably be periodically checking the `clientlist` and maintain a mapping between the cldbid and the current nickname and update that any time one of the two changes.

However, in your use case this would still break if the client changes nicknames offline and reconnects after 30 days. I always assumed the cldbid to be permanent, tracking clients by nickname would be pretty insecure (since anyone can choose any nickname, as long as nobody with the same name is already connected).
