### ISSUE TITLE
AFK channel must be named AFK

### ISSUE THREAD

**Issue by DerEmperor** [Murgeye/teamspeak3-python-bot#14]
Setting the global variable does not work, because you overwrite it with a function default value called 'AFK'. 
Maybe see my 'fixing': https://github.com/DerEmperor/teamspeak3-python-bot.

BTW Thank you very much for this.

**Comment by Murgeye** [comment]
Thanks for posting this issue, I never ran into this since our AFK channel was always named AFK.

The AFKmover is bit weird in how it handles the channel anyway (why is it a global variable?), and I should probably clean this up when I have the time.

By the way, you have based your fork on the stale master branch (my mistake by not making that clear) and not the use_pip_api branch (that is now called main). In addition to using the (pip) installed version of the API, I also did some cleanup in that branch.

Anyway, I have just fixed this on the active branch (which I have now set as the default branch and renamed to main).
